version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

workflows:
  version: 2.1
  test:
    jobs:
      - test-py27
      - test-py35
      - test-py36
      - test-py371
jobs:
  test-py371: &test-template
    working_directory: ~/pygraceplot
    docker:
      - image: circleci/python:3.7.1 # every job must define an image for the docker executor and subsequent jobs may define a different image.
        environment:
          PIPENV_VENV_IN_PROJECT: false
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
            pip install pytest pytest-cov codecov coverage
      - run:
          command: |
            export PYTHONPATH="~/pygraceplot:$PYTHONPATH"
            python -m pytest --cov=./ --cov-report=xml
      - codecov/upload:
          file: coverage.xml
  test-py36: &test-template
    working_directory: ~/pygraceplot
    docker:
      - image: circleci/python:3.6 # every job must define an image for the docker executor and subsequent jobs may define a different image.
        environment:
          PIPENV_VENV_IN_PROJECT: false
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
            pip install pytest
      - run:
          command: |
            export PYTHONPATH="~/pygraceplot:$PYTHONPATH"
            python -m pytest
  test-py35: &test-template
    working_directory: ~/pygraceplot
    docker:
      - image: circleci/python:3.5 # every job must define an image for the docker executor and subsequent jobs may define a different image.
        environment:
          PIPENV_VENV_IN_PROJECT: false
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.5/site-packages
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
            pip install pytest
      - run:
          command: |
            export PYTHONPATH="~/pygraceplot:$PYTHONPATH"
            python -m pytest
  test-py27: &test-template
    working_directory: ~/pygraceplot
    docker:
      - image: circleci/python:2.7 # every job must define an image for the docker executor and subsequent jobs may define a different image.
        environment:
          PIPENV_VENV_IN_PROJECT: false
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python2.7/site-packages
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
            pip install pytest
      - run:
          command: |
            export PYTHONPATH="~/pygraceplot:$PYTHONPATH"
            python -m pytest
